package tp1.clases.controlador;

public enum Escena {
    MENU_PRINCIPAL, MENU_HABILIDADES, PANTALLA_EFECTO, MENU_POKEMONES, PANTALLA_SELECCION_POKEMON, PANTALLA_APLICAR_ITEM, MENU_ITEMS, POKEMON_MUERTO;
}
